// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtVECgi9xH9OQoqDBORHzOYaFiW2Vd7Lg',
    appId: '1:842547781074:web:b45bf16caf1d55abdcbc0b',
    messagingSenderId: '842547781074',
    projectId: 'zoom-clone-5979b',
    authDomain: 'zoom-clone-5979b.firebaseapp.com',
    storageBucket: 'zoom-clone-5979b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-tXlyEP3R-MsZFAcaP6-_iLB-krGnriU',
    appId: '1:842547781074:android:777b4e9c8cde5fe1dcbc0b',
    messagingSenderId: '842547781074',
    projectId: 'zoom-clone-5979b',
    storageBucket: 'zoom-clone-5979b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwSnLLk3ecIlYApudy01ad8du1y94hH1s',
    appId: '1:842547781074:ios:efe8817d3114e40ddcbc0b',
    messagingSenderId: '842547781074',
    projectId: 'zoom-clone-5979b',
    storageBucket: 'zoom-clone-5979b.appspot.com',
    iosClientId: '842547781074-epmng2u5crdmr9afac37q7hfvh34ut82.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwSnLLk3ecIlYApudy01ad8du1y94hH1s',
    appId: '1:842547781074:ios:efe8817d3114e40ddcbc0b',
    messagingSenderId: '842547781074',
    projectId: 'zoom-clone-5979b',
    storageBucket: 'zoom-clone-5979b.appspot.com',
    iosClientId: '842547781074-epmng2u5crdmr9afac37q7hfvh34ut82.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
